services:
  workspace:
    container_name: workspace-container
    build:
      context: ./docker/workspace
    volumes:
      - ../:/home/vscode/workspace:cached
    working_dir: /workspace
    tty: true

  mysql:
    container_name: mysql-container
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTHOR_API_DB_ROOT_PASSWORD:-thisIsReallyStrongPassword123}
      MYSQL_DATABASE: ${AUTHOR_API_DB_DATABASE:-dev}
      MYSQL_USER: ${AUTHOR_API_DB_USER:-mysql}
      MYSQL_PASSWORD: ${AUTHOR_API_DB_PASSWORD:-thisIsReallyStrongPassword123}
